language: cpp

# Install newer version of CMake as the one that comes preinstalled on
# travis-ci doesn't support CMakeAddFortranSubdirectory.
before_install:
  - wget http://www.cmake.org/files/v2.8/cmake-2.8.12.2-Linux-i386.tar.gz

install:
  - tar xzf cmake-2.8.12.2-Linux-i386.tar.gz
  - sudo apt-get update
  - sudo apt-get install libc6:i386 gfortran unixodbc-dev

script:
  - cmake-2.8.12.2-Linux-i386/bin/cmake -DBUILD=all .
  - make -j3
  - make test
